
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int DIGITOS = 69;
  public static final int PR_DE_LO_CONTRARIO = 10;
  public static final int SB_CORCHETE_LEFT = 53;
  public static final int PR_FIN_SI = 12;
  public static final int SB_INTERROGACION_LEFT = 60;
  public static final int OP_MENOR_QUE = 48;
  public static final int PR_O_SI = 11;
  public static final int PR_FIN = 3;
  public static final int PR_FUNCION = 32;
  public static final int OP_NOT = 40;
  public static final int OP_AND = 38;
  public static final int PR_INGRESAR = 4;
  public static final int PR_FIN_PARA = 20;
  public static final int OP_MULTIPLICACION = 43;
  public static final int PR_FIN_SEGUN = 15;
  public static final int SB_INTERROGACION_RIGHT = 61;
  public static final int OP_POTENCIA = 45;
  public static final int PR_CON_VALOR = 6;
  public static final int IDENTIFICADOR = 66;
  public static final int PR_RETORNAR = 25;
  public static final int PR_CADENA = 35;
  public static final int CARACTER = 64;
  public static final int PR_SEGUN = 13;
  public static final int PR_HASTA_QUE = 24;
  public static final int PR_HACER = 14;
  public static final int PR_INCREMENTAL = 19;
  public static final int PR_EJECUTAR = 26;
  public static final int PR_PARA = 16;
  public static final int PR_ASIGNACION = 7;
  public static final int PR_BOOLEAN = 36;
  public static final int BOOLEAN = 65;
  public static final int PR_CON = 18;
  public static final int EOF = 0;
  public static final int OP_DIVISION = 44;
  public static final int COMENTARIO2 = 63;
  public static final int error = 1;
  public static final int PR_FIN_FUNCION = 33;
  public static final int COMENTARIO1 = 62;
  public static final int yycolumn = 59;
  public static final int SB_PARENTESIS_LEFT = 55;
  public static final int PR_IMPRIMIR = 27;
  public static final int CADENA = 68;
  public static final int OP_OR = 39;
  public static final int OP_ES_DIFERENTE = 50;
  public static final int OP_RESTA = 42;
  public static final int SB_PUNTO_Y_COMA = 57;
  public static final int PR_INICIO = 2;
  public static final int PR_ENTONCES = 9;
  public static final int OP_MAYOR_IGUAL = 51;
  public static final int SB_CORCHETE_RIGHT = 54;
  public static final int OP_MODULO = 46;
  public static final int PR_IMPRIMIR_NL = 28;
  public static final int OP_IGUAL = 49;
  public static final int PR_CARACTER = 37;
  public static final int PR_NUMERO = 34;
  public static final int SB_PARENTESIS_RIGHT = 56;
  public static final int PR_HASTA = 17;
  public static final int PR_CON_PARAMETROS = 30;
  public static final int OP_MENOR_IGUAL = 52;
  public static final int OP_MAYOR_QUE = 47;
  public static final int PR_REPETIR = 23;
  public static final int SB_COMA = 58;
  public static final int PR_MIENTRAS = 21;
  public static final int CARACTER_E = 67;
  public static final int OP_SUMA = 41;
  public static final int PR_FIN_METODO = 31;
  public static final int PR_METODO = 29;
  public static final int PR_SI = 8;
  public static final int PR_COMO = 5;
  public static final int PR_FIN_MIENTRAS = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PR_INICIO",
  "PR_FIN",
  "PR_INGRESAR",
  "PR_COMO",
  "PR_CON_VALOR",
  "PR_ASIGNACION",
  "PR_SI",
  "PR_ENTONCES",
  "PR_DE_LO_CONTRARIO",
  "PR_O_SI",
  "PR_FIN_SI",
  "PR_SEGUN",
  "PR_HACER",
  "PR_FIN_SEGUN",
  "PR_PARA",
  "PR_HASTA",
  "PR_CON",
  "PR_INCREMENTAL",
  "PR_FIN_PARA",
  "PR_MIENTRAS",
  "PR_FIN_MIENTRAS",
  "PR_REPETIR",
  "PR_HASTA_QUE",
  "PR_RETORNAR",
  "PR_EJECUTAR",
  "PR_IMPRIMIR",
  "PR_IMPRIMIR_NL",
  "PR_METODO",
  "PR_CON_PARAMETROS",
  "PR_FIN_METODO",
  "PR_FUNCION",
  "PR_FIN_FUNCION",
  "PR_NUMERO",
  "PR_CADENA",
  "PR_BOOLEAN",
  "PR_CARACTER",
  "OP_AND",
  "OP_OR",
  "OP_NOT",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTIPLICACION",
  "OP_DIVISION",
  "OP_POTENCIA",
  "OP_MODULO",
  "OP_MAYOR_QUE",
  "OP_MENOR_QUE",
  "OP_IGUAL",
  "OP_ES_DIFERENTE",
  "OP_MAYOR_IGUAL",
  "OP_MENOR_IGUAL",
  "SB_CORCHETE_LEFT",
  "SB_CORCHETE_RIGHT",
  "SB_PARENTESIS_LEFT",
  "SB_PARENTESIS_RIGHT",
  "SB_PUNTO_Y_COMA",
  "SB_COMA",
  "yycolumn",
  "SB_INTERROGACION_LEFT",
  "SB_INTERROGACION_RIGHT",
  "COMENTARIO1",
  "COMENTARIO2",
  "CARACTER",
  "BOOLEAN",
  "IDENTIFICADOR",
  "CARACTER_E",
  "CADENA",
  "DIGITOS"
  };
}

